[package]
name = "aoc_2024_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1"
rayon = "1.10"

[profile.release]
opt-level = 3               # Use slightly better optimizations.
overflow-checks = false
